dataloader:
  training:
    csv_path: /home/sei2clj/threed-reconstruction/ml/Dataset/train.csv
    sample_n_times: 4
    video_folder: /mnt/hddmount1/sei2clj/HQ339
    condition_folder: /mnt/hddmount1/sei2clj/HQ339
    sample_n_frames: 7
  validation:
    csv_path: /home/sei2clj/threed-reconstruction/ml/Dataset/train.csv
    video_folder: /mnt/hddmount1/sei2clj/HQ339
    condition_folder: /mnt/hddmount1/sei2clj/HQ339
    sample_n_times: 1
    sample_n_frames: 14
    height: 256
    width: 256
    steps: 30
  per_gpu_batch_size: 1
  num_of_workers: 0
  sam_checkpoint: /home/sei2clj/threed-reconstruction/ml/SegmentAnything/segment-anything/weights/sam_vit_h_4b8939.pth

trainer:
  output_dir: training_version_1
  logging_dir: logs
  gradient_accumulation_steps: 4
  mixed_precision: fp16
  seed: 1234421
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: False
  allow_tf32: False
  checkpointing_steps: 30
  checkpoints_total_limit: 3
  num_train_epochs: 160
  max_train_steps:
  optimizer:
    scale_lr: False
    learning_rate: 2.e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 1.e-2
    adam_epsilon: 1.e-08
    lr_scheduler: constant
    lr_warmup_steps: 500 

logger:
  tensorboard_path: /home/sei2clj/threed-reconstruction/ml/Train/tensorboard
  name: ControlStableVideoDiffusion

model:
  pretrained_model_name_or_path: stabilityai/stable-video-diffusion-img2vid
  revision: None
  pretrain_unet: None
  controlnet_model_name_or_path: CiaraRowles/temporal-controlnet-depth-svd-v1
  conditioning_dropout_prob: 0.1